version: "3.8"

services:
  backend:
    build:
      context: ./backend/python_back/
    env_file:
      - ./backend/python_back/.env
    ports:
      - "5000:5000"
    restart: unless-stopped

  telegrambot:
    build:
      context: ./frontend/bot/
    env_file:
      - ./frontend/bot/.env
    ports:
      - "8080:8080"  
    restart: unless-stopped
    depends_on:
      - backend